const mongoose = require('mongoose')

const resumeSchema = mongoose.Schema({
    introduction:{
        name:{
            type:String,
            required:true
        },
    },

    contact:{
        phone:{
            type:String,
            required:true,
        },
        email:{
            type:String,
            required:true,
        },
        location:{
            type:String,
            required:true,
        },
    },
    socials:{
        linkedin:String,
        twitter:String,
        instagram:String,
        github:String,
    },
    summary:{
        type:String,
    },
    projects:[{
        title:{
            type:String,
            required:true,
        },
        about:{
            type:String,
            required:true,
        },
        link:{
            type:String,
            required:true,
        },
        tech:[{
            type:String,
            required:true,
        }],
    }],
    skills:[{
        type:String,
        required:true,
    }],
    experience:[{
        jobTitle:{
            type:String,
            required:true,
        },
        aboutJob:{
            type:String,
            required:true
        },
        timeLine:{
            type:String,    
            required:true
        },
    }],
    education:[{
        degree:{
            type:String,
            required:true,
        },
        whatYouDid:{
            type:String,
            required:true,
        },
        yearOfGraduation:{
            type:String,
            required:true
        }
    }]
}, {timestamps:true})

module.exports = mongoose.model("Resume", resumeSchema)